#!/usr/bin/env python3

import subprocess
import sys


pathToFx = "/home/djoe/Documents/javaFXV19/javafx-sdk-19/lib" # Edit this to your javafx downloaded path bruh

prgName = sys.argv[1]
className = sys.argv[1][:-5]
print("Program Name --> " + prgName)
print("Class Name Must Be --> " + className)


print("\n\n")
print("-"*50)
print("Compiling..")
print("-"*50)

subprocess.call("javac --module-path " + pathToFx + " --add-modules javafx.controls " + prgName, shell=True)

print("-"*50)
print("Executing..")
print("-"*50)

print("\n")
print("-"*50)
print("OUTPUT GOES HERE : (You may get error if there is an error in your java program). Check Compiling Section")
print("-"*50)



subprocess.call("java --module-path " + pathToFx + " --add-modules javafx.controls "+ className, shell=True)
